### ISSUE TITLE
Finalize archive (.pkg) format

### ISSUE THREAD

**Issue by creekorful** [go-pkg-org/gopkg#3]
# Source package

/usr/share/gopkg.org/src/***import-path***/***files***

# Binary package

/usr/local/bin/***program***

**Comment by creekorful** [comment]
@Johannestegner Little note: I think we should store the go import path into *Metadata* struct, so that in build step we can easily reconstruct the import path when making the source (-dev) package

**Comment by Johannestegner** [comment]
Yes that might be a good idea. :)
