### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by frozzare** [go-pkg-org/gopkg#30]
How should we name packages? 

Right now we have: `github-go-pkg-org-gohello` but it's a bit confusing to have `github` as a part of the name. It will work for different vcs, but maybe not so good for custom import paths, e.g `go.example.com/something`

Some ideas:
- Remove hostname from package name, e.g `go-pkg-org-gohello`
- Allow simple names, e.g `gohello`
- Allow scoped package names, e.g `go-pkg-org/gohello`

**Comment by creekorful** [comment]
I do agree package names are a bit confusing. Here's my opinion:

Binary package (the ones that end users will effectively install) are already using simple name: for example https://github.com/go-pkg-org/gohello will build two packages:

- a source package named github-go-pkg-org-gohello (will only be used by our build infrastructure if needed)
- a binary package named hello (will be installed by end users using `gopkg install`)

As you can see binary package are already using simple form, while source package are verbose to ensure maximum unicity.

We cannot use scope packages name like you've proposed because '/' is a path separator and may induce a lot of bugs later one.
But maybe we can remove host from package name like you have suggested, I'm not sure wether host should be part of the unicity. What are your opinions @go-pkg-org/core-maintainers ?

**Comment by Johannestegner** [comment]
It's quite hard yes, if we go with just the name of the binary/package, the package names will be filled up in a first come first served basis. I guess that it would feel kind of okay when it comes to some specific (really large) packages that already have their name as a trademark so to speak... but I would think that people would create their own type of scopes after a while (like with what happened to NPM).

If the `/` is an issue, we might be able to use something else, or even make it possible to have multiple packages with the same name, and in such a case give the user a choice:

```
There are 12349834 packages named 'test', did you mean:
1) test - by Johannes
2) test - by SomeoneElse
3) test - by Super-Cool-Releasegroup
```

While we (in the backend) then would store it depending on the maintainers (with a group entry in the metadata).

**Comment by frozzare** [comment]
We can still use host in the name, but we need support all kind of hosts and I don't think we should remove the tld, e.g just convert `github.com/go-pkg-org/hello` to `github-com-go-pkg-org-hello`, then we won't have issues with `go.example.com/hello` or something else.

But I think we need to support scopes since we will have packages with the same name quite fast and if we want this to grow we can't be limited to simple names. Scopes can also be good to tell where the package is from, e.g `example-inc/hello` will probably be `github.com/example-inc/hello` or something, or be more accurate by having the vcs in the name, e.g `gopkg install github/example-inc/hello`

`/` may be an issue but I think we can work around it and match it with our backend somehow. 

I'm just worried about that we will end up having name conflicts quite fast if we don't have a solid ground where have tough how we can scope packages somehow. Npm did it quite well with `@example/package`

**Comment by creekorful** [comment]
I have taken some time to think about the issue, here's my thought:

Let's start with end users use case (install binary package), we should have the simplest way of identifying package while prevent any conflict. There have been some conflicts on Debian with package name, ending up in crappy solution to prevent that (adding prefix, suffix, etc...). I agree with @frozzare idea to scope the package.

For my example I'll suppose that users want to install the following (wonderful package BTW) package https://github.com/muesli/duf.

# Binary package

The followings:

```
$ gopkg install muesli/duf
```

looks the best for end users. We will ensure unicity while preventing any name clashes. Plus is it easy to find where's the package coming from.

This package will be built on the following form:

```
muesli-duf_1.0.0-1_linux_amd64.pkg
```

and stored in the following way on the archive:

```
/github.com/muesli/duf/muesli-duf_1.0.0-1_linux_amd64.pkg
```

# Source package

Let's take the previous example and suppose that https://github.com/muesli/duf is exposing a API (and therefore a src package)

The followings:

```
$ gopkg install-dev github.com/muesli/duf
```

TODO

This package will be built on the following form:

```
github.com-muesli-duf_1.0.0-1_dev.pkg
```

and stored in the following way on the archive:

```
/github.com/muesli/duf/github.com-muesli-duf_1.0.0-1_dev.pkg
```

What do you think @go-pkg-org/core-maintainers ?

**Comment by frozzare** [comment]
I like it, let's continue on this approach!

**Comment by creekorful** [comment]
Great! Let's see what @Johannestegner think about this, and if its good for him too, I'll assign myself the issue & implement the changes on a separate branch

**Comment by Johannestegner** [comment]
I agree. Might need some "ownership" in the backend to be created, but that's all good.
