### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by Johannestegner** [go-pkg-org/gopkg#34]
All good CLI's have globally persistent configurations (hehe, no, but most package managers have one or another way of doing it), this is a proposition for a `.gopkg` configuration file to put in the `user.HomeDir` which contains globally saved configurations.

This could include stuff like paths where the user want to store installed binaries or sources, but also stuff like maintainer information and gpg key id's that could be used when the user creates a new package.  

A simple yaml file would suffice.

**Comment by creekorful** [comment]
I do agree with @Johannestegner, here's what the config file should contains (at least for now)

- maintainer_name : (currently env variable GOPKG_MAINTAINER_NAME) The maintainer name
- maintainer_email : (currently env variable GOPKG_MAINTAINER_EMAIL) The maintainer email
- bin_dir: (create env variable like GOPKG_BIN_DIR) The place where to install binary. Defaults to the `getBinaryInstallDir` logic
- src_dir (create env variable like GOPKG_SRC_DIR) The place where to install source directory. Defaults to the `getSourceInstallDir`logic

It could be great to create a special package with method that try to read the value from config file, and if not presents fallback to env variable, and if not present fallback to built-in logic.

Using yaml format and storing the file under $HOME/.gopkg.yml looks the bests AFAIK
